In [1]:
import csv
import zipfile
import os
import io
import pandas as pd

# Directory containing zip files
directory = 'D:\\SEC_Trading_Bot_Dataset\\'
# Output CSV file path
output_file_path = 'D:\\SEC_Trading_Bot_Dataset\\cleaned_sec_form_4_dataset_2006_to_2023.csv'

# Mapping of transaction codes to descriptions
# example: print(trans_code_map["P"]) => Open market or private purchase of non-derivative or derivative security
trans_code_map = {
    "A": "Grant, award or other acquisition pursuant to Rule 16b-3(d)",
    "C": "Conversion of derivative security",
    "D": "Disposition to the issuer of issuer equity securities pursuant to Rule 16b-3(e)",
    "E": "Expiration of short derivative position",
    "F": "Payment of exercise price or tax liability by delivering or withholding securities incident to the receipt, exercise or vesting of a security issued in accordance with Rule 16b-3",
    "G": "Bona fide gift",
    "H": "Expiration (or cancellation) of long derivative position with value received",
    "I": "Discretionary transaction in accordance with Rule 16b-3(f) resulting in acquisition or disposition of issuer securities",
    "J": "Other acquisition or disposition (describe transaction)",
    "L": "Small acquisition under Rule 16a-6",
    "M": "Exercise or conversion of derivative security exempted pursuant to Rule 16b-3",
    "O": "Exercise of out-of-the-money derivative security",
    "P": "Open market or private purchase of non-derivative or derivative security",
    "S": "Open market or private sale of non-derivative or derivative security",
    "U": "Disposition pursuant to a tender of shares in a change of control transaction",
    "W": "Acquisition or disposition by will or the laws of descent and distribution",
    "X": "Exercise of in-the-money or at-the-money derivative security",
    "Z": "Deposit into or withdrawal from voting trust"
}

In [3]:
cleaned_sec_form_4_dataset_2006_to_2023 = pd.DataFrame()

for folder in os.listdir(directory):
    if not folder.endswith('.zip'):
        continue

    # Extract the zip file
    with zipfile.ZipFile(directory + folder, 'r') as zip_ref:
        zip_ref.extractall(directory)

        # Read the TSV files into DataFrames
        submission_df = pd.read_csv(directory + 'SUBMISSION.tsv', delimiter='\t')
        reporting_owner_df = pd.read_csv(directory + 'REPORTINGOWNER.tsv', delimiter='\t')
        nonderiv_df = pd.read_csv(directory + 'NONDERIV_TRANS.tsv', delimiter='\t')
        nonderiv_holding_df = pd.read_csv(directory + 'NONDERIV_HOLDING.tsv', delimiter='\t')
        deriv_df = pd.read_csv(directory + 'DERIV_TRANS.tsv', delimiter='\t')
        deriv_holding_df = pd.read_csv(directory + 'DERIV_HOLDING.tsv', delimiter='\t')

        # add ND_T_ prefix to all columns in nonderiv_df except ACCESSION_NUMBER and NONDERIV_TRANS_SK
        nonderiv_df.columns = ['ND_T_' + col if col not in ['ACCESSION_NUMBER', 'NONDERIV_TRANS_SK'] else col for col in nonderiv_df.columns]

        # add ND_H_ prefix to all columns in nonderiv_holding_df except ACCESSION_NUMBER and NONDERIV_HOLDING_SK
        nonderiv_holding_df.columns = ['ND_H_' + col if col not in ['ACCESSION_NUMBER', 'NONDERIV_HOLDING_SK'] else col for col in nonderiv_holding_df.columns]

        # add D_T_ prefix to all columns in deriv_df except ACCESSION_NUMBER and DERIV_TRANS_SK
        deriv_df.columns = ['D_T_' + col if col not in ['ACCESSION_NUMBER', 'DERIV_TRANS_SK'] else col for col in deriv_df.columns]

        # add D_H_ prefix to all columns in deriv_holding_df except ACCESSION_NUMBER and DERIV_HOLDING_SK
        deriv_holding_df.columns = ['D_H_' + col if col not in ['ACCESSION_NUMBER', 'DERIV_HOLDING_SK'] else col for col in deriv_holding_df.columns]

        # Filter for Form 4 filings
        form_4_submission_df = submission_df[submission_df['DOCUMENT_TYPE'].isin(['4'])]

        # Merge datasets based on common keys
        merged_df = pd.merge(form_4_submission_df, reporting_owner_df, on=['ACCESSION_NUMBER'], how='inner')
        merged_df = pd.merge(merged_df, nonderiv_df, on=['ACCESSION_NUMBER'], how='inner')
        merged_df = pd.merge(merged_df, nonderiv_holding_df, on=['ACCESSION_NUMBER'], how='inner')
        merged_df = pd.merge(merged_df, deriv_df, on=['ACCESSION_NUMBER'], how='inner')
        merged_df = pd.merge(merged_df, deriv_holding_df, on=['ACCESSION_NUMBER'], how='inner')

        # Select desired features
        features_to_keep = [
                'ACCESSION_NUMBER','FILING_DATE', 'PERIOD_OF_REPORT', 'ISSUERTRADINGSYMBOL',
                'ND_T_TRANS_DATE', 'ND_T_TRANS_CODE', 'ND_T_EQUITY_SWAP_INVOLVED', 'ND_T_TRANS_SHARES', 'ND_T_TRANS_PRICEPERSHARE', 'ND_T_TRANS_ACQUIRED_DISP_CD', 'ND_T_SHRS_OWND_FOLWNG_TRANS', 'ND_T_DIRECT_INDIRECT_OWNERSHIP',
                'ND_H_SHRS_OWND_FOLWNG_TRANS', 'ND_H_DIRECT_INDIRECT_OWNERSHIP',
                'D_T_TRANS_DATE', 'D_T_TRANS_CODE', 'D_T_TRANS_SHARES', 'D_T_TRANS_PRICEPERSHARE', 'D_T_TRANS_ACQUIRED_DISP_CD', 'D_T_SHRS_OWND_FOLWNG_TRANS', 'D_T_DIRECT_INDIRECT_OWNERSHIP',
                'D_H_SHRS_OWND_FOLWNG_TRANS', 'D_H_DIRECT_INDIRECT_OWNERSHIP'
            ]

        final_df = merged_df[features_to_keep]

        # Handle missing data as required (e.g., drop rows, fillna, etc.)
        folder_date = folder[0:6]
        # Save or process the final merged DataFrame as needed
        final_df.to_csv(folder_date + '_merged_form_4_data.csv', index=False)

        cleaned_sec_form_4_dataset_2006_to_2023 = cleaned_sec_form_4_dataset_2006_to_2023.append(final_df, ignore_index=True)

cleaned_sec_form_4_dataset_2006_to_2023.to_csv(output_file_path, index=False)

c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (13,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,23,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (17,21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,19,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (13,17,21,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,13,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (19,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,14,15,19,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,19,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,9,14,19,37,39) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (15,19,33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,9,14,15,19,33,37,39) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,15,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,13,19,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,15,19,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,15,19,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (7,13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (19,33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,15,33) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (9,19,33,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
# print col types and null values for each column
print(cleaned_sec_form_4_dataset_2006_to_2023.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4887497 entries, 0 to 4887496
Data columns (total 23 columns):
 #   Column                          Dtype
---  ------                          -----
 0   ACCESSION_NUMBER                object
 1   FILING_DATE                     object
 2   PERIOD_OF_REPORT                object
 3   ISSUERTRADINGSYMBOL             object
 4   ND_T_TRANS_DATE                 object
 5   ND_T_TRANS_CODE                 object
 6   ND_T_EQUITY_SWAP_INVOLVED       object
 7   ND_T_TRANS_SHARES               float64
 8   ND_T_TRANS_PRICEPERSHARE        float64
 9   ND_T_TRANS_ACQUIRED_DISP_CD     object
 10  ND_T_SHRS_OWND_FOLWNG_TRANS     float64
 11  ND_T_DIRECT_INDIRECT_OWNERSHIP  object
 12  ND_H_SHRS_OWND_FOLWNG_TRANS     float64
 13  ND_H_DIRECT_INDIRECT_OWNERSHIP  object
 14  D_T_TRANS_DATE                  object
 15  D_T_TRANS_CODE                  object
 16  D_T_TRANS_SHARES                float64
 17  D_T_TRANS_PRICEPERSHARE         float64
 18  D_T_TRANS_ACQUIRED_DISP_CD      object
 19  D_T_SHRS_OWND_FOLWNG_TRANS      float64
 20  D_T_DIRECT_INDIRECT_OWNERSHIP   object
 21  D_H_SHRS_OWND_FOLWNG_TRANS      float64
 22  D_H_DIRECT_INDIRECT_OWNERSHIP   object
dtypes: float64(8), object(15)
memory usage: 857.6+ MB
None

In [6]:
all_data = pd.read_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_sec_form_4_dataset_2006_to_2023.csv")

c:\Users\ericb\anaconda3\envs\ML_Torch\lib\site-packages\IPython\core\interactiveshell.py:3524: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

# Seeing the number of missing values vs total rows

We will remove rows from cols that have very few missing values (less than 10%).

We will remove cols from the dataset that have more than 10% missing values.

We want data without any missing values to train our model efficiently.

In [10]:
def calculate_missing_values(data):
    # Calculate the number of missing values in each column
    missing_values = data.isnull().sum()

    # Calculate the total number of rows
    total_rows = data.shape[0]

    # Print the number of missing values in each column vs the total number of rows
    for column in missing_values.index:
        print(f'{column}: {missing_values[column]} missing values out of {total_rows} rows ({missing_values[column] / total_rows * 100:.2f}%)')

calculate_missing_values(cleaned_sec_form_4_dataset_2006_to_2023)

ACCESSION_NUMBER: 0 missing values out of 4887497 rows (0.00%)
FILING_DATE: 0 missing values out of 4887497 rows (0.00%)
PERIOD_OF_REPORT: 0 missing values out of 4887497 rows (0.00%)
ISSUERTRADINGSYMBOL: 513 missing values out of 4887497 rows (0.01%)
ND_T_TRANS_DATE: 0 missing values out of 4887497 rows (0.00%)
ND_T_TRANS_CODE: 0 missing values out of 4887497 rows (0.00%)
ND_T_EQUITY_SWAP_INVOLVED: 0 missing values out of 4887497 rows (0.00%)
ND_T_TRANS_SHARES: 0 missing values out of 4887497 rows (0.00%)
ND_T_TRANS_PRICEPERSHARE: 770808 missing values out of 4887497 rows (15.77%)
ND_T_TRANS_ACQUIRED_DISP_CD: 0 missing values out of 4887497 rows (0.00%)
ND_T_SHRS_OWND_FOLWNG_TRANS: 129 missing values out of 4887497 rows (0.00%)
ND_T_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 4887497 rows (0.00%)
ND_H_SHRS_OWND_FOLWNG_TRANS: 37 missing values out of 4887497 rows (0.00%)
ND_H_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 4887497 rows (0.00%)
D_T_TRANS_DATE: 0 missing values out of 4887497 rows (0.00%)
D_T_TRANS_CODE: 0 missing values out of 4887497 rows (0.00%)
D_T_TRANS_SHARES: 4779 missing values out of 4887497 rows (0.10%)
D_T_TRANS_PRICEPERSHARE: 810024 missing values out of 4887497 rows (16.57%)
D_T_TRANS_ACQUIRED_DISP_CD: 0 missing values out of 4887497 rows (0.00%)
D_T_SHRS_OWND_FOLWNG_TRANS: 11574 missing values out of 4887497 rows (0.24%)
D_T_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 4887497 rows (0.00%)
D_H_SHRS_OWND_FOLWNG_TRANS: 8713 missing values out of 4887497 rows (0.18%)
D_H_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 4887497 rows (0.00%)

In [11]:
# Drop any rows with missing values in ISSUERTRADINGSYMBOL
all_data = all_data.dropna(subset=['ISSUERTRADINGSYMBOL', 'ND_T_SHRS_OWND_FOLWNG_TRANS', 'ND_H_SHRS_OWND_FOLWNG_TRANS', 'D_T_TRANS_PRICEPERSHARE', 'ND_T_TRANS_PRICEPERSHARE', 'D_T_TRANS_SHARES','D_T_SHRS_OWND_FOLWNG_TRANS','D_H_SHRS_OWND_FOLWNG_TRANS'])

calculate_missing_values(all_data)

ACCESSION_NUMBER: 0 missing values out of 3918767 rows (0.00%)
FILING_DATE: 0 missing values out of 3918767 rows (0.00%)
PERIOD_OF_REPORT: 0 missing values out of 3918767 rows (0.00%)
ISSUERTRADINGSYMBOL: 0 missing values out of 3918767 rows (0.00%)
ND_T_TRANS_DATE: 0 missing values out of 3918767 rows (0.00%)
ND_T_TRANS_CODE: 0 missing values out of 3918767 rows (0.00%)
ND_T_EQUITY_SWAP_INVOLVED: 0 missing values out of 3918767 rows (0.00%)
ND_T_TRANS_SHARES: 0 missing values out of 3918767 rows (0.00%)
ND_T_TRANS_PRICEPERSHARE: 0 missing values out of 3918767 rows (0.00%)
ND_T_TRANS_ACQUIRED_DISP_CD: 0 missing values out of 3918767 rows (0.00%)
ND_T_SHRS_OWND_FOLWNG_TRANS: 0 missing values out of 3918767 rows (0.00%)
ND_T_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 3918767 rows (0.00%)
ND_H_SHRS_OWND_FOLWNG_TRANS: 0 missing values out of 3918767 rows (0.00%)
ND_H_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 3918767 rows (0.00%)
D_T_TRANS_DATE: 0 missing values out of 3918767 rows (0.00%)
D_T_TRANS_CODE: 0 missing values out of 3918767 rows (0.00%)
D_T_TRANS_SHARES: 0 missing values out of 3918767 rows (0.00%)
D_T_TRANS_PRICEPERSHARE: 0 missing values out of 3918767 rows (0.00%)
D_T_TRANS_ACQUIRED_DISP_CD: 0 missing values out of 3918767 rows (0.00%)
D_T_SHRS_OWND_FOLWNG_TRANS: 0 missing values out of 3918767 rows (0.00%)
D_T_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 3918767 rows (0.00%)
D_H_SHRS_OWND_FOLWNG_TRANS: 0 missing values out of 3918767 rows (0.00%)
D_H_DIRECT_INDIRECT_OWNERSHIP: 0 missing values out of 3918767 rows (0.00%)

In [12]:
all_data.to_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_sec_form_4_dataset_2006_to_2023.csv", index=False)

# Convert Categorical Values to One Hot Encoding

In [33]:
all_data = pd.read_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_sec_form_4_dataset_2006_to_2023.csv")

In [13]:
# Print columns in the dataset and number of columns
print(all_data.info())
print(all_data.columns)
print(len(all_data.columns))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3918767 entries, 0 to 4887496
Data columns (total 23 columns):
 #   Column                          Dtype
---  ------                          -----
 0   ACCESSION_NUMBER                object
 1   FILING_DATE                     object
 2   PERIOD_OF_REPORT                object
 3   ISSUERTRADINGSYMBOL             object
 4   ND_T_TRANS_DATE                 object
 5   ND_T_TRANS_CODE                 object
 6   ND_T_EQUITY_SWAP_INVOLVED       object
 7   ND_T_TRANS_SHARES               float64
 8   ND_T_TRANS_PRICEPERSHARE        float64
 9   ND_T_TRANS_ACQUIRED_DISP_CD     object
 10  ND_T_SHRS_OWND_FOLWNG_TRANS     float64
 11  ND_T_DIRECT_INDIRECT_OWNERSHIP  object
 12  ND_H_SHRS_OWND_FOLWNG_TRANS     float64
 13  ND_H_DIRECT_INDIRECT_OWNERSHIP  object
 14  D_T_TRANS_DATE                  object
 15  D_T_TRANS_CODE                  object
 16  D_T_TRANS_SHARES                float64
 17  D_T_TRANS_PRICEPERSHARE         float64
 18  D_T_TRANS_ACQUIRED_DISP_CD      object
 19  D_T_SHRS_OWND_FOLWNG_TRANS      float64
 20  D_T_DIRECT_INDIRECT_OWNERSHIP   object
 21  D_H_SHRS_OWND_FOLWNG_TRANS      float64
 22  D_H_DIRECT_INDIRECT_OWNERSHIP   object
dtypes: float64(8), object(15)
memory usage: 717.5+ MB
None
Index(['ACCESSION_NUMBER', 'FILING_DATE', 'PERIOD_OF_REPORT',
       'ISSUERTRADINGSYMBOL', 'ND_T_TRANS_DATE', 'ND_T_TRANS_CODE',
       'ND_T_EQUITY_SWAP_INVOLVED', 'ND_T_TRANS_SHARES',
       'ND_T_TRANS_PRICEPERSHARE', 'ND_T_TRANS_ACQUIRED_DISP_CD',
       'ND_T_SHRS_OWND_FOLWNG_TRANS', 'ND_T_DIRECT_INDIRECT_OWNERSHIP',
       'ND_H_SHRS_OWND_FOLWNG_TRANS', 'ND_H_DIRECT_INDIRECT_OWNERSHIP',
       'D_T_TRANS_DATE', 'D_T_TRANS_CODE', 'D_T_TRANS_SHARES',
       'D_T_TRANS_PRICEPERSHARE', 'D_T_TRANS_ACQUIRED_DISP_CD',
       'D_T_SHRS_OWND_FOLWNG_TRANS', 'D_T_DIRECT_INDIRECT_OWNERSHIP',
       'D_H_SHRS_OWND_FOLWNG_TRANS', 'D_H_DIRECT_INDIRECT_OWNERSHIP'],
      dtype='object')
23

In [14]:
all_data_one_hot_encoded = pd.get_dummies(all_data, columns=['ND_T_TRANS_CODE', 'ND_T_EQUITY_SWAP_INVOLVED', 'ND_T_TRANS_ACQUIRED_DISP_CD', 'ND_T_DIRECT_INDIRECT_OWNERSHIP', 'ND_H_DIRECT_INDIRECT_OWNERSHIP', 'D_T_TRANS_CODE', 'D_T_TRANS_ACQUIRED_DISP_CD', 'D_T_DIRECT_INDIRECT_OWNERSHIP', 'D_H_DIRECT_INDIRECT_OWNERSHIP'])

print(all_data_one_hot_encoded.info())
print(all_data_one_hot_encoded.columns)
print(len(all_data_one_hot_encoded.columns))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3918767 entries, 0 to 4887496
Data columns (total 66 columns):
 #   Column                            Dtype
---  ------                            -----
 0   ACCESSION_NUMBER                  object
 1   FILING_DATE                       object
 2   PERIOD_OF_REPORT                  object
 3   ISSUERTRADINGSYMBOL               object
 4   ND_T_TRANS_DATE                   object
 5   ND_T_TRANS_SHARES                 float64
 6   ND_T_TRANS_PRICEPERSHARE          float64
 7   ND_T_SHRS_OWND_FOLWNG_TRANS       float64
 8   ND_H_SHRS_OWND_FOLWNG_TRANS       float64
 9   D_T_TRANS_DATE                    object
 10  D_T_TRANS_SHARES                  float64
 11  D_T_TRANS_PRICEPERSHARE           float64
 12  D_T_SHRS_OWND_FOLWNG_TRANS        float64
 13  D_H_SHRS_OWND_FOLWNG_TRANS        float64
 14  ND_T_TRANS_CODE_A                 uint8
 15  ND_T_TRANS_CODE_C                 uint8
 16  ND_T_TRANS_CODE_D                 uint8
 17  ND_T_TRANS_CODE_E                 uint8
 18  ND_T_TRANS_CODE_F                 uint8
 19  ND_T_TRANS_CODE_G                 uint8
 20  ND_T_TRANS_CODE_I                 uint8
 21  ND_T_TRANS_CODE_J                 uint8
 22  ND_T_TRANS_CODE_L                 uint8
 23  ND_T_TRANS_CODE_M                 uint8
 24  ND_T_TRANS_CODE_O                 uint8
 25  ND_T_TRANS_CODE_P                 uint8
 26  ND_T_TRANS_CODE_S                 uint8
 27  ND_T_TRANS_CODE_U                 uint8
 28  ND_T_TRANS_CODE_W                 uint8
 29  ND_T_TRANS_CODE_X                 uint8
 30  ND_T_TRANS_CODE_Z                 uint8
 31  ND_T_EQUITY_SWAP_INVOLVED_0       uint8
 32  ND_T_EQUITY_SWAP_INVOLVED_1       uint8
 33  ND_T_EQUITY_SWAP_INVOLVED_0       uint8
 34  ND_T_EQUITY_SWAP_INVOLVED_1       uint8
 35  ND_T_EQUITY_SWAP_INVOLVED_false   uint8
 36  ND_T_EQUITY_SWAP_INVOLVED_true    uint8
 37  ND_T_TRANS_ACQUIRED_DISP_CD_A     uint8
 38  ND_T_TRANS_ACQUIRED_DISP_CD_D     uint8
 39  ND_T_DIRECT_INDIRECT_OWNERSHIP_D  uint8
 40  ND_T_DIRECT_INDIRECT_OWNERSHIP_I  uint8
 41  ND_H_DIRECT_INDIRECT_OWNERSHIP_D  uint8
 42  ND_H_DIRECT_INDIRECT_OWNERSHIP_I  uint8
 43  D_T_TRANS_CODE_A                  uint8
 44  D_T_TRANS_CODE_C                  uint8
 45  D_T_TRANS_CODE_D                  uint8
 46  D_T_TRANS_CODE_E                  uint8
 47  D_T_TRANS_CODE_F                  uint8
 48  D_T_TRANS_CODE_G                  uint8
 49  D_T_TRANS_CODE_H                  uint8
 50  D_T_TRANS_CODE_I                  uint8
 51  D_T_TRANS_CODE_J                  uint8
 52  D_T_TRANS_CODE_M                  uint8
 53  D_T_TRANS_CODE_O                  uint8
 54  D_T_TRANS_CODE_P                  uint8
 55  D_T_TRANS_CODE_S                  uint8
 56  D_T_TRANS_CODE_U                  uint8
 57  D_T_TRANS_CODE_W                  uint8
 58  D_T_TRANS_CODE_X                  uint8
 59  D_T_TRANS_CODE_Z                  uint8
 60  D_T_TRANS_ACQUIRED_DISP_CD_A      uint8
 61  D_T_TRANS_ACQUIRED_DISP_CD_D      uint8
 62  D_T_DIRECT_INDIRECT_OWNERSHIP_D   uint8
 63  D_T_DIRECT_INDIRECT_OWNERSHIP_I   uint8
 64  D_H_DIRECT_INDIRECT_OWNERSHIP_D   uint8
 65  D_H_DIRECT_INDIRECT_OWNERSHIP_I   uint8
dtypes: float64(8), object(6), uint8(52)
memory usage: 642.8+ MB
None
Index(['ACCESSION_NUMBER', 'FILING_DATE', 'PERIOD_OF_REPORT',
       'ISSUERTRADINGSYMBOL', 'ND_T_TRANS_DATE', 'ND_T_TRANS_SHARES',
       'ND_T_TRANS_PRICEPERSHARE', 'ND_T_SHRS_OWND_FOLWNG_TRANS',
       'ND_H_SHRS_OWND_FOLWNG_TRANS', 'D_T_TRANS_DATE', 'D_T_TRANS_SHARES',
       'D_T_TRANS_PRICEPERSHARE', 'D_T_SHRS_OWND_FOLWNG_TRANS',
       'D_H_SHRS_OWND_FOLWNG_TRANS', 'ND_T_TRANS_CODE_A', 'ND_T_TRANS_CODE_C',
       'ND_T_TRANS_CODE_D', 'ND_T_TRANS_CODE_E', 'ND_T_TRANS_CODE_F',
       'ND_T_TRANS_CODE_G', 'ND_T_TRANS_CODE_I', 'ND_T_TRANS_CODE_J',
       'ND_T_TRANS_CODE_L', 'ND_T_TRANS_CODE_M', 'ND_T_TRANS_CODE_O',
       'ND_T_TRANS_CODE_P', 'ND_T_TRANS_CODE_S', 'ND_T_TRANS_CODE_U',
       'ND_T_TRANS_CODE_W', 'ND_T_TRANS_CODE_X', 'ND_T_TRANS_CODE_Z',
       'ND_T_EQUITY_SWAP_INVOLVED_0', 'ND_T_EQUITY_SWAP_INVOLVED_1',
       'ND_T_EQUITY_SWAP_INVOLVED_0', 'ND_T_EQUITY_SWAP_INVOLVED_1',
       'ND_T_EQUITY_SWAP_INVOLVED_false', 'ND_T_EQUITY_SWAP_INVOLVED_true',
       'ND_T_TRANS_ACQUIRED_DISP_CD_A', 'ND_T_TRANS_ACQUIRED_DISP_CD_D',
       'ND_T_DIRECT_INDIRECT_OWNERSHIP_D', 'ND_T_DIRECT_INDIRECT_OWNERSHIP_I',
       'ND_H_DIRECT_INDIRECT_OWNERSHIP_D', 'ND_H_DIRECT_INDIRECT_OWNERSHIP_I',
       'D_T_TRANS_CODE_A', 'D_T_TRANS_CODE_C', 'D_T_TRANS_CODE_D',
       'D_T_TRANS_CODE_E', 'D_T_TRANS_CODE_F', 'D_T_TRANS_CODE_G',
       'D_T_TRANS_CODE_H', 'D_T_TRANS_CODE_I', 'D_T_TRANS_CODE_J',
       'D_T_TRANS_CODE_M', 'D_T_TRANS_CODE_O', 'D_T_TRANS_CODE_P',
       'D_T_TRANS_CODE_S', 'D_T_TRANS_CODE_U', 'D_T_TRANS_CODE_W',
       'D_T_TRANS_CODE_X', 'D_T_TRANS_CODE_Z', 'D_T_TRANS_ACQUIRED_DISP_CD_A',
       'D_T_TRANS_ACQUIRED_DISP_CD_D', 'D_T_DIRECT_INDIRECT_OWNERSHIP_D',
       'D_T_DIRECT_INDIRECT_OWNERSHIP_I', 'D_H_DIRECT_INDIRECT_OWNERSHIP_D',
       'D_H_DIRECT_INDIRECT_OWNERSHIP_I'],
      dtype='object')
66

# Handling Malformed Dates

Some data has the year 0015, which is not a valid year. We will drop these.

In [15]:
def convert_date(date_str):
    try:
        return pd.to_datetime(date_str, format='%d-%b-%Y')
    except Exception:
        return date_str

bad_dates = all_data_one_hot_encoded['ND_T_TRANS_DATE'].apply(convert_date)
bad_dates = bad_dates[bad_dates.apply(lambda x: isinstance(x, str))]
print(bad_dates)

2046461    23-NOV-0015
2046462    23-NOV-0015
2046463    23-NOV-0015
2046464    23-NOV-0015
2046465    23-NOV-0015
2046466    23-NOV-0015
2046467    23-NOV-0015
2046468    23-NOV-0015
2046469    24-NOV-0015
2046470    24-NOV-0015
2046471    24-NOV-0015
2046472    24-NOV-0015
2046473    24-NOV-0015
2046474    24-NOV-0015
2046475    24-NOV-0015
2046476    24-NOV-0015
2046477    23-NOV-0015
2046478    23-NOV-0015
2046479    23-NOV-0015
2046480    23-NOV-0015
2046481    23-NOV-0015
2046482    23-NOV-0015
2046483    23-NOV-0015
2046484    23-NOV-0015
Name: ND_T_TRANS_DATE, dtype: object

In [21]:
# delete rows 2046461 - 2046484
all_data_one_hot_encoded = all_data_one_hot_encoded.drop(index=range(2046461, 2046485))

In [22]:
# Convert Dates to DateTime (original format is DD-MON-YYYY)
all_data_one_hot_encoded['FILING_DATE'] = pd.to_datetime(all_data_one_hot_encoded['FILING_DATE'], format='%d-%b-%Y')
all_data_one_hot_encoded['PERIOD_OF_REPORT'] = pd.to_datetime(all_data_one_hot_encoded['PERIOD_OF_REPORT'], format='%d-%b-%Y')
all_data_one_hot_encoded['ND_T_TRANS_DATE'] = pd.to_datetime(all_data_one_hot_encoded['ND_T_TRANS_DATE'], format='%d-%b-%Y')
all_data_one_hot_encoded['D_T_TRANS_DATE'] = pd.to_datetime(all_data_one_hot_encoded['D_T_TRANS_DATE'], format='%d-%b-%Y')

print(all_data_one_hot_encoded.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3918695 entries, 0 to 4887496
Data columns (total 66 columns):
 #   Column                            Dtype
---  ------                            -----
 0   ACCESSION_NUMBER                  object
 1   FILING_DATE                       datetime64[ns]
 2   PERIOD_OF_REPORT                  datetime64[ns]
 3   ISSUERTRADINGSYMBOL               object
 4   ND_T_TRANS_DATE                   datetime64[ns]
 5   ND_T_TRANS_SHARES                 float64
 6   ND_T_TRANS_PRICEPERSHARE          float64
 7   ND_T_SHRS_OWND_FOLWNG_TRANS       float64
 8   ND_H_SHRS_OWND_FOLWNG_TRANS       float64
 9   D_T_TRANS_DATE                    datetime64[ns]
 10  D_T_TRANS_SHARES                  float64
 11  D_T_TRANS_PRICEPERSHARE           float64
 12  D_T_SHRS_OWND_FOLWNG_TRANS        float64
 13  D_H_SHRS_OWND_FOLWNG_TRANS        float64
 14  ND_T_TRANS_CODE_A                 uint8
 15  ND_T_TRANS_CODE_C                 uint8
 16  ND_T_TRANS_CODE_D                 uint8
 17  ND_T_TRANS_CODE_E                 uint8
 18  ND_T_TRANS_CODE_F                 uint8
 19  ND_T_TRANS_CODE_G                 uint8
 20  ND_T_TRANS_CODE_I                 uint8
 21  ND_T_TRANS_CODE_J                 uint8
 22  ND_T_TRANS_CODE_L                 uint8
 23  ND_T_TRANS_CODE_M                 uint8
 24  ND_T_TRANS_CODE_O                 uint8
 25  ND_T_TRANS_CODE_P                 uint8
 26  ND_T_TRANS_CODE_S                 uint8
 27  ND_T_TRANS_CODE_U                 uint8
 28  ND_T_TRANS_CODE_W                 uint8
 29  ND_T_TRANS_CODE_X                 uint8
 30  ND_T_TRANS_CODE_Z                 uint8
 31  ND_T_EQUITY_SWAP_INVOLVED_0       uint8
 32  ND_T_EQUITY_SWAP_INVOLVED_1       uint8
 33  ND_T_EQUITY_SWAP_INVOLVED_0       uint8
 34  ND_T_EQUITY_SWAP_INVOLVED_1       uint8
 35  ND_T_EQUITY_SWAP_INVOLVED_false   uint8
 36  ND_T_EQUITY_SWAP_INVOLVED_true    uint8
 37  ND_T_TRANS_ACQUIRED_DISP_CD_A     uint8
 38  ND_T_TRANS_ACQUIRED_DISP_CD_D     uint8
 39  ND_T_DIRECT_INDIRECT_OWNERSHIP_D  uint8
 40  ND_T_DIRECT_INDIRECT_OWNERSHIP_I  uint8
 41  ND_H_DIRECT_INDIRECT_OWNERSHIP_D  uint8
 42  ND_H_DIRECT_INDIRECT_OWNERSHIP_I  uint8
 43  D_T_TRANS_CODE_A                  uint8
 44  D_T_TRANS_CODE_C                  uint8
 45  D_T_TRANS_CODE_D                  uint8
 46  D_T_TRANS_CODE_E                  uint8
 47  D_T_TRANS_CODE_F                  uint8
 48  D_T_TRANS_CODE_G                  uint8
 49  D_T_TRANS_CODE_H                  uint8
 50  D_T_TRANS_CODE_I                  uint8
 51  D_T_TRANS_CODE_J                  uint8
 52  D_T_TRANS_CODE_M                  uint8
 53  D_T_TRANS_CODE_O                  uint8
 54  D_T_TRANS_CODE_P                  uint8
 55  D_T_TRANS_CODE_S                  uint8
 56  D_T_TRANS_CODE_U                  uint8
 57  D_T_TRANS_CODE_W                  uint8
 58  D_T_TRANS_CODE_X                  uint8
 59  D_T_TRANS_CODE_Z                  uint8
 60  D_T_TRANS_ACQUIRED_DISP_CD_A      uint8
 61  D_T_TRANS_ACQUIRED_DISP_CD_D      uint8
 62  D_T_DIRECT_INDIRECT_OWNERSHIP_D   uint8
 63  D_T_DIRECT_INDIRECT_OWNERSHIP_I   uint8
 64  D_H_DIRECT_INDIRECT_OWNERSHIP_D   uint8
 65  D_H_DIRECT_INDIRECT_OWNERSHIP_I   uint8
dtypes: datetime64[ns](4), float64(8), object(2), uint8(52)
memory usage: 642.8+ MB
None

In [23]:
cleaned_one_hot_sec_data_2006_to_2023 = all_data_one_hot_encoded.to_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_one_hot_sec_data_2006_to_2023.csv", index=False)

In [15]:
date_columns = ['FILING_DATE', 'PERIOD_OF_REPORT', 'ND_T_TRANS_DATE', 'D_T_TRANS_DATE']

cleaned_one_hot_sec_data_2006_to_2023 = pd.read_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_one_hot_sec_data_2006_to_2023.csv", parse_dates=date_columns)

In [16]:
len(cleaned_one_hot_sec_data_2006_to_2023)

3918695

## Reducing dataset size by removing rows

Deleting all rows where the filing date is more than 2 days after the due date.

In [28]:
# delete all rows where the FILING_DATE value is more than 2 days after the PERIOD_OF_REPORT value
cleaned_one_hot_sec_data_2006_to_2023 = cleaned_one_hot_sec_data_2006_to_2023[cleaned_one_hot_sec_data_2006_to_2023['FILING_DATE'] - cleaned_one_hot_sec_data_2006_to_2023['PERIOD_OF_REPORT'] <= pd.Timedelta(days=2)]
print(len(cleaned_one_hot_sec_data_2006_to_2023))

# Create a smaller dataset with only data from 2020 to 2023
sec_data_2020_to_2023 = cleaned_one_hot_sec_data_2006_to_2023[cleaned_one_hot_sec_data_2006_to_2023['FILING_DATE'].dt.year >= 2020]
print(len(sec_data_2020_to_2023))

1744062
440722

In [29]:
# Save
cleaned_one_hot_sec_data_2006_to_2023.to_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\cleaned_one_hot_sec_data_2006_to_2023.csv", index=False)
cleaned_one_hot_sec_data_2006_to_2023.head()

# Save
sec_data_2020_to_2023.to_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\sec_data_2020_to_2023.csv", index=False)
sec_data_2020_to_2023.head()

,ACCESSION_NUMBER,FILING_DATE,PERIOD_OF_REPORT,ISSUERTRADINGSYMBOL,ND_T_TRANS_DATE,ND_T_TRANS_SHARES,ND_T_TRANS_PRICEPERSHARE,ND_T_SHRS_OWND_FOLWNG_TRANS,ND_H_SHRS_OWND_FOLWNG_TRANS,D_T_TRANS_DATE,...,D_T_TRANS_CODE_U,D_T_TRANS_CODE_W,D_T_TRANS_CODE_X,D_T_TRANS_CODE_Z,D_T_TRANS_ACQUIRED_DISP_CD_A,D_T_TRANS_ACQUIRED_DISP_CD_D,D_T_DIRECT_INDIRECT_OWNERSHIP_D,D_T_DIRECT_INDIRECT_OWNERSHIP_I,D_H_DIRECT_INDIRECT_OWNERSHIP_D,D_H_DIRECT_INDIRECT_OWNERSHIP_I
2587559,0001439288-20-000019,2020-01-31,2020-01-30,RXN,2020-01-30,110000.0,33.65,46576.0,3383.0,2020-01-30,...,0,0,0,0,0,1,1,0,1,0
2587560,0001439288-20-000019,2020-01-31,2020-01-30,RXN,2020-01-30,110000.0,33.65,46576.0,3383.0,2020-01-30,...,0,0,0,0,0,1,1,0,1,0
2587561,0001439288-20-000019,2020-01-31,2020-01-30,RXN,2020-01-30,110000.0,33.65,46576.0,3383.0,2020-01-30,...,0,0,0,0,0,1,1,0,1,0
2587562,0001439288-20-000019,2020-01-31,2020-01-30,RXN,2020-01-30,110000.0,33.65,46576.0,3383.0,2020-01-30,...,0,0,0,0,0,1,1,0,1,0
2587563,0001439288-20-000019,2020-01-31,2020-01-30,RXN,2020-01-30,110000.0,22.03,156576.0,3383.0,2020-01-30,...,0,0,0,0,0,1,1,0,1,0

# Create a Toy Dataset for Testing the Storm Topology

We will create a toy dataset with 10 rows

In [21]:
# create a toy dataset with 10 random rows
toy_dataset = cleaned_one_hot_sec_data_2006_to_2023.sample(10)

toy_dataset.head(10)

,ACCESSION_NUMBER,FILING_DATE,PERIOD_OF_REPORT,ISSUERTRADINGSYMBOL,ND_T_TRANS_DATE,ND_T_TRANS_SHARES,ND_T_TRANS_PRICEPERSHARE,ND_T_SHRS_OWND_FOLWNG_TRANS,ND_H_SHRS_OWND_FOLWNG_TRANS,D_T_TRANS_DATE,...,D_T_TRANS_CODE_U,D_T_TRANS_CODE_W,D_T_TRANS_CODE_X,D_T_TRANS_CODE_Z,D_T_TRANS_ACQUIRED_DISP_CD_A,D_T_TRANS_ACQUIRED_DISP_CD_D,D_T_DIRECT_INDIRECT_OWNERSHIP_D,D_T_DIRECT_INDIRECT_OWNERSHIP_I,D_H_DIRECT_INDIRECT_OWNERSHIP_D,D_H_DIRECT_INDIRECT_OWNERSHIP_I
3629482,0001562180-22-000965,2022-02-02,2022-01-31,JBHT,2022-01-31,291.0,192.54,15398.00,8111.00,2022-01-31,...,0,0,0,0,0,1,1,0,1,0
118502,0000065011-06-000057,2006-05-04,2006-05-03,MDP,2006-05-03,4597.0,48.76,178470.00,5994.00,2006-05-03,...,0,0,0,0,0,1,1,0,1,0
1779408,0001140361-15-001167,2015-01-08,2015-01-06,MNST,2015-01-06,23504.0,111.64,124483.00,401148.00,2015-01-07,...,0,0,0,0,0,1,0,1,1,0
2550407,0001381668-19-000062,2019-08-20,2019-08-19,TFSL,2019-08-19,86778.0,18.00,142622.00,6200.00,2019-08-19,...,0,0,0,0,0,1,1,0,1,0
1414494,0001127602-13-006297,2013-02-15,2013-02-13,HY,2013-02-13,9007.0,0.00,177544.00,61768.00,2013-02-08,...,0,0,0,0,0,1,0,1,0,1
3524219,0001127602-21-027822,2021-10-29,2021-10-27,UHS,2021-10-28,35690.0,126.17,83252.00,55763.00,2021-10-27,...,0,0,0,0,1,0,0,1,0,1
2009624,0001140361-16-089190,2016-12-09,2016-12-07,SMMF,2016-12-08,1200.0,29.00,59168.00,10905.09,2016-12-08,...,0,0,0,0,0,1,1,0,1,0
1135479,0001209191-11-005072,2011-01-26,2011-01-24,ANDE,2011-01-24,8400.0,39.12,15805.59,2025.00,2011-01-24,...,0,0,0,0,0,1,1,0,1,0
1955978,0001127602-16-051693,2016-05-10,2016-05-08,HVT,2016-02-29,1351.0,0.00,51381.00,603497.00,2016-05-08,...,0,0,0,0,0,1,1,0,1,0
3918439,0001562180-23-007490,2023-11-02,2023-10-31,JBHT,2023-10-31,289.0,0.00,15075.00,2428.00,2023-10-31,...,0,0,0,0,0,1,1,0,1,0

In [22]:
# save the toy dataset to a CSV file
toy_dataset.to_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\toy_dataset.csv", index=False)

In [23]:
# Read toy dataset
toy_dataset = pd.read_csv("D:\\SEC_Trading_Bot_Dataset\\Cleaned_Data\\toy_dataset.csv")



# Print the first 5 rows of the DataFrame
print(toy_dataset.head())

       ACCESSION_NUMBER FILING_DATE PERIOD_OF_REPORT ISSUERTRADINGSYMBOL  \
0  0001562180-22-000965  2022-02-02       2022-01-31                JBHT
1  0000065011-06-000057  2006-05-04       2006-05-03                 MDP
2  0001140361-15-001167  2015-01-08       2015-01-06                MNST
3  0001381668-19-000062  2019-08-20       2019-08-19                TFSL
4  0001127602-13-006297  2013-02-15       2013-02-13                  HY

  ND_T_TRANS_DATE  ND_T_TRANS_SHARES  ND_T_TRANS_PRICEPERSHARE  \
0      2022-01-31              291.0                    192.54
1      2006-05-03             4597.0                     48.76
2      2015-01-06            23504.0                    111.64
3      2019-08-19            86778.0                     18.00
4      2013-02-13             9007.0                      0.00

   ND_T_SHRS_OWND_FOLWNG_TRANS  ND_H_SHRS_OWND_FOLWNG_TRANS D_T_TRANS_DATE  \
0                      15398.0                       8111.0     2022-01-31
1                     178470.0                       5994.0     2006-05-03
2                     124483.0                     401148.0     2015-01-07
3                     142622.0                       6200.0     2019-08-19
4                     177544.0                      61768.0     2013-02-08

   ...  D_T_TRANS_CODE_U  D_T_TRANS_CODE_W  D_T_TRANS_CODE_X  \
0  ...                 0                 0                 0
1  ...                 0                 0                 0
2  ...                 0                 0                 0
3  ...                 0                 0                 0
4  ...                 0                 0                 0

   D_T_TRANS_CODE_Z  D_T_TRANS_ACQUIRED_DISP_CD_A  \
0                 0                             0
1                 0                             0
2                 0                             0
3                 0                             0
4                 0                             0

   D_T_TRANS_ACQUIRED_DISP_CD_D  D_T_DIRECT_INDIRECT_OWNERSHIP_D  \
0                             1                                1
1                             1                                1
2                             1                                0
3                             1                                1
4                             1                                0

   D_T_DIRECT_INDIRECT_OWNERSHIP_I  D_H_DIRECT_INDIRECT_OWNERSHIP_D  \
0                                0                                1
1                                0                                1
2                                1                                1
3                                0                                1
4                                1                                0

   D_H_DIRECT_INDIRECT_OWNERSHIP_I
0                                0
1                                0
2                                0
3                                0
4                                1

[5 rows x 66 columns]

In [27]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MDP&interval=30min&month=2009-05&extended_hours=false&datatype=csv&apikey=UXZP610LHWPUM71M&outputsize=full'

r = requests.get(url)
data = r.content.decode('utf-8')

print(data)

{
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
}